swagger: '2.0'
info:
  version: '1.0'
  title: "Product Management API"
  description: Basic API for managing products
  license:
    name: MIT
    url: https://github.com/apiaryio/product-api/blob/master/LICENSE
host: localhost:8080
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /products:
    get:
      tags:
        - Products
      summary: List All Products
      description: Retrieve a list of all products
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
          examples:
            application/json:
              - id: "09"
                type: "CREDIT_CARD"
                name: "Gem Visa"
                version: "v1"
              - id: "10"
                type: "CREDIT_CARD" 
                name: "28 Degrees"
                version: "v1"
              - id: "11"
                type: "PERSONAL_LOAN"
                name: "MyFlexiPay"
                version: "v2"

  /product/{id}:
    get:
      tags:
        - Products
      summary: Get Product Details
      description: Retrieve details of a specific product
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: Product ID
      responses:
        200:
          description: Successful Response
          schema:
            $ref: '#/definitions/Product'
        404:
          description: Product Not Found
          schema:
            $ref: '#/definitions/Error'

definitions:
  Product:
    type: object
    properties:
      id:
        type: string
        description: Product identifier
      type:
        type: string
        description: Product type (e.g. CREDIT_CARD, PERSONAL_LOAN)
        enum: [CREDIT_CARD, PERSONAL_LOAN, MICHAEL_TRAN, DON_HO, HIP]
      name:
        type: string
        description: Product name
      version:
        type: string
        description: Product version
    required:
      - id
      - type
      - name
      - version
    example:
      id: "09"
      type: "CREDIT_CARD"
      name: "Gem Visa"
      version: "v1"

  Error:
    type: object
    properties:
      message:
        type: string
    required:
      - message
    example:
      message: "Product not found"

tags:
  - name: Products
    description: Product management endpoints